# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0f04df4472c83b98f5336ba9434775338dcca7a01d53358d39e3e140384c90a3f1e273ffb7b7616c4c098a388e301929e1ba34118c511cfd57d82cb4c8d37f3

test:
  secret_key_base: 44ad28fac0dca4a5713485c500d1d2e32c111ca8e71137a51c9c4533cf148ca6f3cac8d1a009434a3aec89f8260b8a5383e095e0341630aa8d8d0a9ecf52ab7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
